### PR TITLE
Add option to replace the original file with -f flag

### PR DESCRIPTION
**Pull request by marcinkrzeminski**
Hi,

with your code adjustments and a little bit of research, I was able to implement the `-f`, `--force` flag. By providing this flag as a first argument you can now replace the original file.

Feel free to refactor my code if it's crap ;). Like I said before I'm not a Python dev.

Examples:

Single file
```
crunch -f file.png
```

Directory recursive
```
find. -name "*.png" | xargs crunch -f
```

Tested on macOS Catalina, Version: 10.15.1 (19B88)

### CODE REVIEW

**Comment by chrissimpkins** [comment]
Thank you very much!!  I will have a look and try to add tests this week so that we can get this merged.  I really appreciate it!

**Comment by chrissimpkins** [comment]
I pushed these changes to the `dev` branch Marcin. Thank you very much for this work!  I made some very minor edits to your source contribution here in https://github.com/chrissimpkins/Crunch/commit/02b5e456704dce0df873c562629134c66592448a.

I still need to add new tests for the inplace file write functionality before we merge this to master.  I am also thinking through how we might include this in the GUI and macOS services.  Perhaps through a config file?  Let's see.

I'd like to examine a handful of upstream changes that have happened in zopfli since our last release.  I may try to roll that into a release that includes your new force/inplace overwrite support here.  

Thanks again!  We'll get this out soon!

**Comment by marcinkrzeminski** [comment]
Thanks for letting me know :).

As of GUI, I'd suggest a checkbox if possible. Config file seems a bit cumbersome, especially for less experienced users which are more likely to use the GUI version, instead of the command line.

**Comment by chrissimpkins** [comment]
> As of GUI, I'd suggest a checkbox if possible. Config file seems a bit cumbersome, especially for less experienced users which are more likely to use the GUI version, instead of the command line.

Absolutely agree.  This will require a full rewrite of the GUI application.  It is just an automated wrapper around the Python script at the moment and I don't have a way to implement the settings configuration.  Looking into this.

**Pull request merged**
