### PR TITLE
Add Linux support

### PR DESCRIPTION
**Pull request by perillamint**
Add Linux support. Tested on ArchLinux with pngquant and zopflipng from AUR.

### CODE REVIEW

**Comment by chrissimpkins** [comment]
Thanks for all of this work @perillamint!  I've been tossing around how to approach this as a command line executable/script on *nix platforms and updated this thread last week:

https://github.com/chrissimpkins/Crunch/issues/4

Thoughts about using pinned versions of pngquant and zopflipng that are built off of the system PATH rather than system PATH installed (and by definition for many/most Linux users who install with a package manager, rolling versions that cannot be tested to confirm that they work/produce images as intended with the current approach)?  This would provide users with assurance that the approach to image processing will not change unless they upgrade to a new version of Crunch-defined versions of these dependencies.  It would also allow us to provide valid cross-platform benchmarks as Linux/macOS/Win with *nix flavors would all be using the same versions of pngquant and zopflipng as we have pinned in the macOS GUI application & macOS right click menu service. 

It would be fairly simple to add a make target for installation of these optimization dependencies from source and then modify the script here to use those executables rather than the system PATH installed binaries.  The paths might be `~/pngquant/bin/pngquant` and `~/zopflipng/bin/zopflipng`.

I am just tossing around ideas and since you are an interested Linux user, I wanted to bounce this off of you.  I am more than willing to do the above work to implement it and am not asking for changes to the current scripting.  Looking for your thoughts.

For the script, can I ask you to perform a `shellcheck crunch.sh` on it and address any warnings/errors that show up in the lines that you committed here?  These changes will serve as the basis for the work that we will do to implement the above.

Thanks again for your efforts here! Much appreciated!

**Comment by chrissimpkins** [comment]
Side note:

I am planning to add parallel image optimization support and will likely use a Python script to accomplish this. See https://github.com/chrissimpkins/Crunch/issues/17

My thoughts are that the Python script named `crunch` that runs off of `env` defined Python interpreter, provides standard command line `--help`, `--usage`, `--version` information.  The shell script as defined here can be called from the Python script on individual image files after Python tests to determine the need for spawned processes (it is a multiple image request) and availability of multiple processors on the user's system.  Those who don't want a parallel processing approach can use this script directly.

FYI.  More work in the pipeline. This should fit together nicely.

**Comment by perillamint** [comment]
@chrisssimpkins

**Comment by perillamint** [comment]
@chrissimpkins That's why I added PATH=$(dirname "$0"):$PATH

in front of this script. It first tries its local directory for pngquant and zopflipng. If it cannot find them in its directory, it will fall back into system version of them.

**Comment by chrissimpkins** [comment]
I suggest that we install the scripts on PATH in `/usr/local/bin`.  The pngquant and zopflipng executables will be installed off of PATH.  This way users don't need to add a new directory path to their PATH, define an alias, etc. in order to call the shell script / new Python script on the command line or from another script.   This way `crunch` is tied to pinned versions and users can update their package manager installed versions at whatever version they want.  Thoughts?

Let me know if you have the time/interest to continue working on the source.  I created a local branch with your changes and will push it to the remote repo if you want to collaboratively work off of it.  I will dig into the source in more detail this evening.  I haven't had a chance to have a detailed look yet.

**Comment by chrissimpkins** [comment]
1. Added CI testing: https://semaphoreci.com/sourcefoundry/crunch of shell scripts with shellcheck
2. Refactored the `crunch.sh` source to achieve POSIX compliance as per suggestions in shellcheck
3. Pushed this to `dev` branch of the repo

If you perform any further work, please base on these new changes to your commits and rebase this PR on the `dev` branch.  Thanks.

**Comment by perillamint** [comment]
I'll do further development on this weekend. I'll rebase my patch.

Thanks for notification. 

On 5 April 2018 13:18:25 GMT+09:00, Chris Simpkins <notifications@github.com> wrote:
>1. Added CI testing: https://semaphoreci.com/sourcefoundry/crunch of
>shell scripts with shellcheck
>2. Refactored the `crunch.sh` source to achieve POSIX compliance as per
>suggestions in shellcheck
>3. Pushed this to `dev` branch of the repo
>
>If you perform any further work, please base on these new changes to
>your commits and rebase this PR on the `dev` branch.  Thanks.
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/chrissimpkins/Crunch/pull/18#issuecomment-378815945

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by chrissimpkins** [comment]
Your changes here have been merged to `dev` branch and will be part of the v2.0.0 release of Crunch.  Will close this PR as complete and we can take up further work in a new PR if you'd like to contribute other changes (and I highly encourage this if you have the time!).

Thanks for your work here to get this moving forward!

**Comment by chrissimpkins** [comment]
@perillamint see https://github.com/chrissimpkins/Crunch/pull/19 which will be the PR for the work in progress on v2.0.0 if you'd like to contribute further.  Thanks again.

**Comment by chrissimpkins** [comment]
@perillamint initial implementation of *nix command line executable with support for parallel image processing is now available in the dev branch.  Would greatly appreciate any feedback that you have if you have time to test this.  I haven't tried it on a Linux yet.  It is currently working great on macOS.  make based install of dependencies and the executable file are "documented" in the OP of the open pull request #19

**Pull request closed without merging**
