### PR TITLE
Update README.md to show percentage of memory saved

### PR DESCRIPTION
**Pull request by dsouzarc**
For each of the demo pictures in README.md, it might be useful to show the percentage of memory saved by using Crunch's optimizations alongside the Original/Optimized Size and DSSIM similarity score.

Memory saved = (Original_Size - Optimized_Size) / Original_Size

See [Issue 35](https://github.com/chrissimpkins/Crunch/issues/35)

### CODE REVIEW

**Comment by chrissimpkins** [comment]
Thank you very much for this PR Ryan!  These are very useful data.  I must admit I haven't included them in the past because I have to perform manual updates of all of the data each time there are changes that influence file sizes.  As of the v2 release over the weekend, the `crunch` executable reports % original file size.  Can I ask you to revise the values to 1-current value, title it `Percent original size` in the bullet point, and continue to express as a percent so that my maintainer duties only involve running the `crunch` tool and copying the values to the README?  Once that is complete, I will merge this.

Thank you very much!

**Comment by dsouzarc** [comment]
Hey Chris, thank you for your quick reply and kind words :) 

I don't think I fully understood your message so I only changed `Memory saved` to `Percent original size` for now.

Would you like me to remove the '%' as well (i.e.: `66.50%` --> `66.50`)? 

And/or would you like me to redo the formula too? 

I apologize for the misunderstanding but I'd love to help out in any way I can.

**Comment by chrissimpkins** [comment]
No worries at all!  I am just trying to express the value as % of the original file size.  The only thing that we need to change after your latest commit is to calculate `1 - existing value` and use that as the % of the original file size.

Calculation I am after is:

```
(Optimized file size in bytes / Original file size in bytes) * 100
```

These numbers will be the same as we report when files are run through the command line application:

```
$ crunch chug.png source-wordmark.png
Crunching ...
Spawning 2 processes to optimize 2 image files...
[ 24.70% ] image1-crunch.png (5764 bytes)
[ 26.17% ] image2-crunch.png (10111 bytes)
```

You can ignore the test failure.  I added a new make target for testing today that wasn't in your forked branch.  This will not be a problem and you don't need to change anything on your end.

**Comment by chrissimpkins** [comment]
Minor issue.  I can make the modifications.  Thanks again for these changes Ryan!

**Comment by dsouzarc** [comment]
Oh awesome - thank you Chris! Sorry, I wasn't on my laptop earlier otherwise I would've loved to make those changes.

By the way, if you're curious about the (sudden?) influx of PRs/Issues/Stars/Forks or how I found out about Crunch, your repository was recently featured in a newsletter from [Gitlogs](https://www.gitlogs.com/), a site that aggregates the top trending repositories in various languages.

**Comment by chrissimpkins** [comment]
Thanks much Ryan!  No worries at all.  They were simple changes.  They are now live on master.  Check out your changes!

**Pull request merged**
